### ISSUE TITLE
No module named utils

### ISSUE THREAD

**Issue by Stolas** [aaronportnoy/toolbag#10]
When I double click 'find_switch_jumps.py' 
The following returns in my Output window:

[!] Attempted to add an EA that wasn't code.
No module named utils
'module' object has no attribute 'init'
Python>import sys
Python>sys.version
2.7.2 (default, Mar 26 2012, 16:13:09) 
[GCC 4.2.4 (Ubuntu 4.2.4-1ubuntu4)]
Python>sys.path
['/home/stolas/bin/ida-6.6/python/lib/python27.zip', '/home/stolas/bin/ida-6.6/python/lib/python2.7/', '/home/stolas/bin/ida-6.6/python/lib/python2.7/plat-linux2', '/home/stolas/bin/ida-6.6/python/lib/python2.7/lib-tk', '/home/stolas/bin/ida-6.6/python/lib/python2.7/lib-old', '/home/stolas/bin/ida-6.6/python/lib/python2.7/lib-dynload', '/home/stolas/bin/ida-6.6/python', '/home/stolas', '/home/stolas/.idapro', '/home/stolas/.idapro/base', '/home/stolas/.idapro/app', '/home/stolas/.idapro/user', '/home/stolas/.idapro/toolbag', '/home/stolas/.idapro/toolbag/providers', '/home/stolas/.idapro/toolbag/agent/dbg', '/home/stolas/.idapro/toolbag/agent', u'/home/stolas/.idapro/user/bin']

**Comment by aaronportnoy** [comment]
I'd recommend using switchViewer.py which does the same thing. I'm not sure why find_switch_jumps.py is still in the repo--I'll remove it.

**Comment by Stolas** [comment]
Great thank you :)
